name = "Fractals with Numpy and Canvas"
description = "Render Fractals using Numpy, Canvas in Pyscript."
packages = ["numpy", "sympy"]

[files]
"./palettes.py" = ""
"./fractals.py" = ""

[[fetch]]
from = "https://github.com/ShaliniR8/movie-recommendation-1/blob/feat/exp/model.pkl"
name = "Movie Predictions"
